// etsro es para la autentificaciond e clerk
import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { roboto } from "./ui/fonts";
import AuthWrapper from './components/AuthWrapper';
export const metadata: Metadata = {
  // este titulo es de l navegador 
  title: "SonriSoft",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // sirve para  la autentificacion el  clerkprovider
     <ClerkProvider>  
    <html lang="en">
      <body
        className={`${roboto.className}`}
      >
          <AuthWrapper>
            {children}
          </AuthWrapper>
      </body>
    </html>
    </ClerkProvider>
  );
}
